// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium ciliumcidrgroups.cilium.io -A
// kopium version: 0.16.2

use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Serialize, Deserialize};

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, JsonSchema)]
#[kube(group = "cilium.io", version = "v2alpha1", kind = "CiliumCIDRGroup", plural = "ciliumcidrgroups")]
pub struct CiliumCIDRGroupSpec {
    /// ExternalCIDRs is a list of CIDRs selecting peers outside the clusters.
    #[serde(rename = "externalCIDRs")]
    pub external_cid_rs: Vec<String>,
}

