// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium ciliumidentities.cilium.io -A
// kopium version: 0.16.2

use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Serialize, Deserialize};
use std::collections::BTreeMap;

